server:
  port: 8888
  servlet:
    session:
      timeout: PT24H

spring:
  application:
    name: service-ddsyj #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddsyj?useUnicode=true&characterEncoding=utf8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: MySQL
    show-sql: true
    open-in-view: true
